### PR TITLE
Return an object with parsed variables.

### PR DESCRIPTION
**Pull request by firec0der**
In this PR: 
1. a return of an object that is parsed by dotenv.
2. an attempt to assemble an object from `process.env` in a case when .env doesn't exist but variables are defined in `process.env`

### CODE REVIEW

**Comment by rolodato** [comment]
Hi @firec0der, thanks for the PR! I just have a few nitpicky changes to make plus a README update which I'll push to your fork before merging. Before I update the README, could you describe the use case you had in mind for this? It will likely make the description clearer.

**Comment by firec0der** [comment]
Hi!
I use dotenv for building UIs, and I have to use env variables on the client-side.
At least, I hold urls there.

In my case, I do `dotenv.load()`, it returns me an object. After I put that object (or specific values from that) to a json file and after I import those variables to js file.
Why? During a build of an application that js file with values is concated with other project's files. And, I guess, this is the way how to use env variables in client applications.

I have a lot of different variables. And that's why your package is awesome. It checks and stops build in case when some variable wasn't assigned.

I'm not sure that everything is clear. I can make some code snippets if you do want.

**Comment by rolodato** [comment]
Glad you found it helpful :)

I've been thinking about this new feature, and it seems it would be more helpful to always build the object from the environment (based on the variables listed in `.env.example`) instead of leveraging the original return value from `dotenv`. For example, consider this case:

```dosini
# .env.example
TOKEN=
KEY=
```

```dosini
# .env
TOKEN=foo
```

```js
// test.js
console.log(require('dotenv-safe').load());
```

If you do:

```sh
$ KEY=bar node test.js
````

then this will return `{ TOKEN: 'foo' }`, but it seems to be more helpful if we returned `{ TOKEN: 'foo', KEY: 'bar' }`. What do you think?

**Comment by firec0der** [comment]
Yeah, sounds great. I guess, it's the right way.

**Comment by firec0der** [comment]
I can make changes.

**Comment by rolodato** [comment]
Excellent! I'll write up the README, when you make the changes I'll merge and release.

**Comment by firec0der** [comment]
Ok, I'll push changes soon. Thank you!

**Comment by rolodato** [comment]
Actually @firec0der, one more thing if you don't mind - the original behavior from `dotenv` is to return the parsed object in a `parsed` key, like this: https://github.com/motdotla/dotenv/blob/fdd0923e82e12a6e29b65898990201857141e75d/lib/main.js#L66. Could you add it this way instead? That way we can mimic dotenv's behavior as closely as possible.

I think we should leave the error case like we are handling it today though, since the idea is to fail ASAP when missing environment variables are detected. Thanks!

**Comment by rolodato** [comment]
On second thought, I think it makes sense to keep dotenv's `parsed` as-is, i.e. only include what was read from `.env`. I added a second property to the result object called `required` which includes the environment variables required by `.env.example` and fulfilled either by the pre-existing environment or by reading `.env`. I'll push these changes soon and release once dotenv 4.0.0 is published to npm.

**Comment by rolodato** [comment]
Thanks again! Let me know if this approach works out for you.

**Comment by rolodato** [comment]
Released in 4.0.0.

**Pull request merged**
