### PR TITLE
Don't ignore empty variables

### PR DESCRIPTION
**Pull request by reaganthomas**
This is a fix for allowing the use of empty env variables. A great example of this is when using MySQL the default root password is empty on a local box, hence the pull request :)

### CODE REVIEW

**Comment by rolodato** [comment]
Hi @reaganthomas, thanks for the PR. I had considered this but maybe we could add an explicit setting/flag for it. My workflow is basically clone a repo, `cp .env.example .env` and add the environment variables as needed. With the current behavior if I forget to add a variable I get the error I need. What do you think?

**Comment by reaganthomas** [comment]
I'm happy with that as an alternative, and it definitely makes sense for that workflow.

In the `.load` call would passing `allowEmptyString` or similar make sense?

**Comment by rolodato** [comment]
Yes, that sounds good. Maybe `allowEmptyVariables` for the option name?

**Comment by rolodato** [comment]
@reaganthomas ping :)

On a second thought, might be better to have `allowEmptyValues` as the option name, because the keys (variable names) aren't empty, the values are.

**Comment by rolodato** [comment]
Closing in favor of #6, please comment there if needed.

**Pull request closed without merging**
