### PR TITLE
Adds .env.example as a default

### PR DESCRIPTION
**Pull request by motdotla**
Echoing https://github.com/rolodato/dotenv-safe/issues/1

### CODE REVIEW

**Comment by motdotla** [comment]
dotenv-safe is rad @rolodato. Would you consider adding `.env.example` as a default file as well?

**Comment by rolodato** [comment]
I'm not familiar with the convention, but if you feel `.env.example` should be the "canonical way" could you update the readme as well? Thanks for the PR!

**Comment by motdotla** [comment]
Updated @rolodato with a note in the README.

**Comment by rolodato** [comment]
Thanks! I'll make a new release later today.

**Pull request merged**
